<?xml version="1.0"?>
<package format="3">
  <name>ur16_description</name>
  <version>0.0.1</version>
  <description>UR16e + Robotiq 2F-140 description and launch files</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>BSD-3-Clause</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime deps your launch/xacro uses -->
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <!-- UR + Robotiq descriptions used inside xacro -->
  <exec_depend>Universal_Robots_ROS2_Description</exec_depend>
  <exec_depend>robotiq_2f_gripper_description</exec_depend>

  <!-- For get_package_share_directory in the launch file -->
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
